base_dir_detections_fd = './data/your_dataset/base_dir_detections_fd' 
base_dir_detections_cd = './data/your_dataset/base_dir_detections_cd' 
base_dir_groundtruth = './data/your_dataset/base_dir_groundtruth' 
base_dir_metric_fd = './data/your_dataset/base_dir_metric_fd' 
base_dir_metric_cd = './data/your_dataset/base_dir_metric_cd' 
num_actions = 36 # number of grids
num_windows = 3 
img_size_fd = 320 
img_size_cd = 64 
